apiVersion: v1
kind: Service
metadata:
  name: reference-implementation
  namespace: gctoolsv2
  labels:
    name: reference-implementation
  annotations:
    VIRTUAL_HOST: "gctools.lpss.me"
    VIRTUAL_PORT: "80"
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: reference-implementation
